import type { ManifestOptions } from 'vite-plugin-pwa';

/**
 * The Web App Manifest — single source of truth consumed by `vite.config.ts`
 * (`VitePWA({ manifest: pwaManifest })`) and asserted on directly by
 * `manifest.test.ts`, so a future edit that drops a required field (or the
 * app's brand colors) fails a fast unit test instead of only showing up as a
 * missing "Add to Home Screen" prompt.
 *
 * Field choices (M6 spec):
 * - `theme_color`/`background_color` match the in-app coral accent (#f0663f)
 *   and the Login/Home page background (#fbf6f2).
 * - `display: 'standalone'` — installed app hides the browser chrome.
 * - `orientation: 'any'` — the canvas editor is just as usable in either
 *   orientation; nothing about it is portrait/landscape-only.
 * - Icons are self-hosted PNGs generated by `scripts/generate-icons.mjs`
 *   (192/512 + a 512 maskable variant with Android-safe-zone padding).
 */
export const pwaManifest: Partial<ManifestOptions> = {
  name: 'Geurio',
  short_name: 'Geurio',
  description: '중심 주제에서 가지를 뻗어 생각을 정리하는 마인드맵 앱',
  lang: 'ko',
  theme_color: '#f0663f',
  background_color: '#fbf6f2',
  display: 'standalone',
  orientation: 'any',
  /**
   * 앱의 **고유 id**. 없으면 브라우저가 `start_url`을 id로 쓰므로 지금과 같은 값이다
   * (= 이미 설치된 앱의 정체성이 바뀌지 않는다). 명시해 두는 이유는 앞으로
   * `start_url`을 바꿔도 같은 앱으로 남게 하기 위해서다 — id가 바뀌면 브라우저는
   * **다른 앱**으로 보고 중복 설치를 만든다.
   */
  id: '/home',
  // `/home` (not `/`): the root is now the public marketing landing page —
  // an INSTALLED app should launch into the user's documents (RequireAuth
  // still bounces anonymous users to /login).
  start_url: '/home',
  scope: '/',
  icons: [
    { src: '/icons/pwa-192x192.png', sizes: '192x192', type: 'image/png' },
    { src: '/icons/pwa-512x512.png', sizes: '512x512', type: 'image/png' },
    { src: '/icons/maskable-512x512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
  ],
};
