import type { ManifestOptions } from 'vite-plugin-pwa';

/**
 * The Web App Manifest — single source of truth consumed by `vite.config.ts`
 * (`VitePWA({ manifest: pwaManifest })`) and asserted on directly by
 * `manifest.test.ts`, so a future edit that drops a required field (or the
 * app's brand colors) fails a fast unit test instead of only showing up as a
 * missing "Add to Home Screen" prompt.
 *
 * Field choices (M6 spec):
 * - `theme_color`/`background_color` match the in-app coral accent (#f0663f)
 *   and the Login/Home page background (#fbf6f2).
 * - `display: 'standalone'` — installed app hides the browser chrome.
 * - `orientation: 'any'` — the canvas editor is just as usable in either
 *   orientation; nothing about it is portrait/landscape-only.
 * - Icons are self-hosted PNGs generated by `scripts/generate-icons.mjs`
 *   (192/512 + a 512 maskable variant with Android-safe-zone padding).
 */
export const pwaManifest: Partial<ManifestOptions> = {
  name: 'Geurio',
  short_name: 'Geurio',
  description: '중심 주제에서 가지를 뻗어 생각을 정리하는 마인드맵 앱',
  lang: 'ko',
  theme_color: '#f0663f',
  background_color: '#fbf6f2',
  display: 'standalone',
  orientation: 'any',
  start_url: '/',
  scope: '/',
  icons: [
    { src: '/icons/pwa-192x192.png', sizes: '192x192', type: 'image/png' },
    { src: '/icons/pwa-512x512.png', sizes: '512x512', type: 'image/png' },
    { src: '/icons/maskable-512x512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
  ],
};
